(() => {
  'use strict';
  const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const rights={unknown:'Não verificada',own:'Material próprio (vídeo e áudio)',authorized:'Autorizado / licenciado (vídeo e áudio)',unlicensed:'Sem autorização'};
  const restrictions={unknown:'Não conferida',none:'Nenhuma restrição informada',claim_no_impact:'Reivindicação sem impacto no alcance',blocked:'Bloqueado',age:'Restrição de idade',other:'Outra restrição'};
  const opts=(items,value)=>Object.entries(items).map(([k,v])=>`<option value="${k}" ${k===value?'selected':''}>${v}</option>`).join('');
  let assets=Array.from({length:5},()=>({})),uploading=0;
  async function request(url,options){const r=await fetch(url,options),body=await r.json().catch(()=>({}));if(!r.ok)throw Error(typeof body.detail==='string'?body.detail:(body.detail||[]).map(e=>e.msg).join('; ')||'Não foi possível concluir a operação.');return body;}
  const json=(method,data)=>({method,headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});
  document.querySelectorAll('.t5-entry-fields').forEach((field,i)=>{
    field.insertAdjacentHTML('beforeend',`<details class="t5-audio"><summary>Áudio e autorização deste trecho</summary><label>Som de fundo<select id="t5AudioMode${i}">${opts({original:'Manter áudio original',mute:'Silenciar áudio original',replace:'Substituir por arquivo'},'original')}</select></label><div id="t5Replacement${i}" hidden><label>Áudio substituto<input id="t5AudioFile${i}" type="file" accept=".wav,.mp3,.m4a,.ogg,.flac,.aac"></label><small>Até 25 MB. Usa os primeiros 15s, cortados à duração do trecho; se faltar áudio, completa com silêncio.</small><audio id="t5AudioPreview${i}" controls hidden></audio><small id="t5AudioLabel${i}"></small></div><label>Volume do som de fundo (%)<input id="t5AudioVolume${i}" type="number" min="0" max="200" value="100"></label><label>Narração opcional (arquivo)<input id="t5NarrationFile${i}" type="file" accept=".wav,.mp3,.m4a,.ogg,.flac,.aac"></label><small>Começa junto com este trecho. Usa os primeiros 15s. Não gera voz automaticamente.</small><audio id="t5NarrationPreview${i}" controls hidden></audio><small id="t5NarrationLabel${i}"></small><button type="button" class="btn btn-outline btn-sm" id="t5RemoveNarration${i}">Remover narração</button><label>Volume da narração (%)<input id="t5NarrationVolume${i}" type="number" min="0" max="200" value="100"></label><label><input id="t5Ducking${i}" type="checkbox" checked> Reduzir o fundo enquanto a narração toca</label><label>Autorização declarada<select id="t5Rights${i}">${opts(rights,'unknown')}</select></label><label>Notas / referência da licença<input id="t5RightsNotes${i}" maxlength="500" placeholder="Inclua a situação do vídeo e da música"></label><p id="t5AudioStatus${i}" class="t5-tools-status" role="status"></p></details><p id="t5History${i}" class="t5-tools-status" role="status"></p>`);
    $(`t5AudioMode${i}`).onchange=()=>{$(`t5Replacement${i}`).hidden=$(`t5AudioMode${i}`).value!=='replace';};
    for(const [kind,prefix] of [['audio_asset','Audio'],['narration_asset','Narration']]){
      $(`t5${prefix}File${i}`).onchange=async event=>{
        const file=event.target.files[0];if(!file)return;
        const owner=assets[i],token={};owner[kind+'Upload']=token;
        uploading++;$(`t5AudioStatus${i}`).textContent='Preparando áudio…';
        try{if(file.size>25*1024*1024)throw Error('O limite por áudio é 25 MB.');const fd=new FormData();fd.append('file',file);const result=await request('/api/top5-tools/audio',{method:'POST',body:fd});if(assets[i]!==owner||owner[kind+'Upload']!==token)return;owner[kind]=result.asset;showAsset(i,prefix,result.asset,result.name);$(`t5AudioStatus${i}`).textContent='Áudio pronto.';}
        catch(error){if(assets[i]===owner)$(`t5AudioStatus${i}`).textContent=error.message+' O áudio anterior, se houver, foi mantido.';}
        finally{uploading--;event.target.value='';}
      };
    }
    $(`t5RemoveNarration${i}`).onclick=()=>{assets[i].narration_asset=null;assets[i].narration_assetUpload=null;showAsset(i,'Narration',null);};
    let sequence=0;
    $(`t5Url${i}`).addEventListener('change',async()=>{const ticket=++sequence,url=$(`t5Url${i}`).value.trim();$(`t5History${i}`).textContent='';if(!url)return;try{const data=await request('/api/top5-tools/history',json('POST',{urls:[url]}));if(ticket===sequence)$(`t5History${i}`).textContent=data.matches.length?`Já usado em ${data.matches.length} posição(ões): `+data.matches.map(m=>`${m.title} (${m.status})`).join(', '):'Nenhum uso deste link encontrado nos projetos existentes.';}catch{if(ticket===sequence)$(`t5History${i}`).textContent='Histórico indisponível para este link.';}});
  });
  function showAsset(i,prefix,asset,name){const player=$(`t5${prefix}Preview${i}`);player.pause();if(asset)player.src='/api/top5-tools/audio/'+asset;else player.removeAttribute('src');player.hidden=!asset;$(`t5${prefix}Label${i}`).textContent=asset?(name||'Arquivo de áudio salvo'):'';}
  function entry(i){return {audio_mode:$(`t5AudioMode${i}`).value,audio_asset:assets[i].audio_asset||null,narration_asset:assets[i].narration_asset||null,audio_volume:Number($(`t5AudioVolume${i}`).value)/100,narration_volume:Number($(`t5NarrationVolume${i}`).value)/100,ducking:$(`t5Ducking${i}`).checked,rights:$(`t5Rights${i}`).value,rights_notes:$(`t5RightsNotes${i}`).value.trim()};}
  function fill(entries){assets=Array.from({length:5},(_,i)=>({...entries[i]}));for(let i=0;i<5;i++){const e=entries[i]||{};$(`t5AudioMode${i}`).value=e.audio_mode||'original';$(`t5Replacement${i}`).hidden=e.audio_mode!=='replace';$(`t5AudioVolume${i}`).value=(e.audio_volume??1)*100;$(`t5NarrationVolume${i}`).value=(e.narration_volume??1)*100;$(`t5Ducking${i}`).checked=e.ducking!==false;$(`t5Rights${i}`).value=e.rights||'unknown';$(`t5RightsNotes${i}`).value=e.rights_notes||'';showAsset(i,'Audio',e.audio_asset);showAsset(i,'Narration',e.narration_asset);$(`t5AudioStatus${i}`).textContent='';}}
  async function beforeGenerate(spec){
    if(uploading)throw Error('Aguarde o envio dos áudios terminar.');
    spec.entries.forEach((e,i)=>{if(e.audio_mode==='replace'&&!e.audio_asset)throw Error(`Posição ${i+1}: envie o áudio substituto.`);});
    const response=await request('/api/top5-tools/history',json('POST',{urls:spec.entries.map(e=>e.url)}));
    const repeated=spec.entries.filter((e,i,a)=>a.findIndex(x=>x.url===e.url)!==i);
    if(response.matches.length||repeated.length)return confirm(`Há ${response.matches.length} ocorrência(s) em outros rankings e ${repeated.length} link(s) repetido(s) nesta seleção. Deseja gerar mesmo assim?`);
    return true;
  }
  function modal(title){const dialog=document.createElement('dialog');dialog.className='t5-review';dialog.innerHTML=`<header><h2>${title}</h2><button type="button" class="btn btn-outline btn-sm">Fechar</button></header><div class="t5-review-body">Carregando…</div>`;document.body.append(dialog);dialog.querySelector('button').onclick=()=>dialog.close();dialog.onclose=()=>dialog.remove();dialog.showModal();return dialog;}
  async function showReview(job,download){const dialog=modal('Revisão antes de exportar'),body=dialog.querySelector('.t5-review-body');try{const r=await request(`/api/top5-tools/${job.id}/review`);if(!dialog.isConnected)return;job.settings.top5.entries=r.entries;const t=r.technical;
    body.innerHTML=`<p>${esc(r.note)}</p><section><h3>Arquivo final</h3><p>${t?`${t.duration.toFixed(2)}s · ${t.width} × ${t.height} · ${t.fps.toFixed(2)} fps · ${t.has_audio?'faixa de áudio presente':'sem faixa de áudio'}`:'Arquivo não verificado'}</p></section><section><h3>Pontos para revisar</h3><ul>${r.warnings.length?r.warnings.map(w=>`<li>${esc(w)}</li>`).join(''):'<li>Nenhum problema detectado pelas verificações técnicas disponíveis. Isso não confirma direitos de uso.</li>'}</ul></section><section><h3>Fontes e autorizações</h3>${r.entries.map((e,i)=>`<section><strong>${i+1}. ${esc(e.name)}</strong> · <a href="${esc(e.url)}" target="_blank" rel="noopener">Origem ↗</a><p>Áudio: ${esc({original:'original',mute:'silenciado',replace:'substituído'}[e.audio_mode||'original'])}${e.narration_asset?' + narração':''} · Fundo ${Math.round((e.audio_volume??1)*100)}%</p><label>Autorização declarada<select data-rights="${i}">${opts(rights,e.rights||'unknown')}</select></label><label>Notas<input data-notes="${i}" maxlength="500" value="${esc(e.rights_notes||'')}"></label><button class="btn btn-outline btn-sm" data-save-rights="${i}">Salvar autorização</button></section>`).join('')}</section><section><h3>Histórico de uso</h3>${r.history.length?`<ul>${r.history.map(m=>`<li><a href="#/job/${encodeURIComponent(m.job_id)}">${esc(m.title)}</a> · posição ${m.position} · ${esc(m.match)} · ${esc(m.status)}</li>`).join('')}</ul>`:'<p>Nenhuma coincidência nos projetos existentes.</p>'}<p>Compara links/IDs e arquivos idênticos quando há hash salvo. Não reconhece todas as versões recodificadas nem projetos excluídos.</p></section><p class="t5-tools-status" role="status"></p><div class="t5-review-actions">${t?`<a class="btn btn-primary" href="${esc(download||`/api/jobs/${job.id}/clips/top5.mp4`)}" download>Baixar após revisão</a>`:''}</div>`;
    body.querySelectorAll('[data-save-rights]').forEach(button=>button.onclick=async()=>{button.disabled=true;const i=button.dataset.saveRights;try{await request(`/api/top5-tools/${job.id}/rights/${i}`,json('PUT',{rights:body.querySelector(`[data-rights="${i}"]`).value,rights_notes:body.querySelector(`[data-notes="${i}"]`).value}));dialog.close();await showReview(job,download);}catch(error){body.querySelector('[role=status]').textContent=error.message;}finally{button.disabled=false;}});
    body.querySelectorAll('a[href^="#/"]').forEach(a=>a.onclick=()=>dialog.close());
  }catch(error){body.textContent=error.message;}}
  function mount(job,box){
    const actions=box.querySelector('.t5-result-actions');
    actions.querySelectorAll('a').forEach(a=>{const href=a.getAttribute('href');a.textContent=href.endsWith('/download')?'Revisar e baixar pacote':'Revisar e baixar MP4';a.onclick=e=>{e.preventDefault();showReview(job,href);};});
    const section=document.createElement('section');section.className='t5-follow';section.innerHTML=`<h2>Acompanhamento após publicar</h2><p>Registro manual do YouTube Studio. Use métricas acumuladas desde a publicação. Campos vazios significam desconhecido, não zero. A mesma data atualiza o registro existente.</p><form><div class="t5-follow-grid"><label>Data da consulta<input name="date" type="date" required></label><label>Link publicado<input name="video_url" type="url" placeholder="https://youtube.com/shorts/…"></label><label>Restrição no Studio<select name="restriction">${opts(restrictions,'unknown')}</select></label>${[['views','Visualizações totais'],['feed_views','Visualizações pelo Feed dos Shorts'],['shown_in_feed','Exibido no feed'],['average_percentage','Porcentagem média assistida (%)'],['stayed_percentage','Continuaram assistindo (%)']].map(([name,label])=>`<label>${label}<input name="${name}" type="number" min="0" ${name==='stayed_percentage'?'max="100"':''} step="${name.includes('percentage')?'0.01':'1'}"></label>`).join('')}</div><label>Detalhes da restrição / observações<textarea name="notes" maxlength="2000" rows="3"></textarea></label><button class="btn btn-primary" type="submit">Salvar registro</button><p class="t5-tools-status" role="status"></p></form><div class="t5-report-history"></div>`;box.append(section);
    const form=section.querySelector('form'),state=section.querySelector('[role=status]'),history=section.querySelector('.t5-report-history');const now=new Date();form.elements.date.value=`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}-${String(now.getDate()).padStart(2,'0')}`;
    let records=[];
    async function refresh(){const response=await request(`/api/top5-tools/${job.id}/reports`);records=response.reports;history.innerHTML=records.length?'<h3>Registros acumulados (não somados)</h3>'+records.map((r,i)=>`<article><strong>${esc(r.date)} · ${esc(restrictions[r.restriction])}</strong><p>Total: ${r.views??'—'} · Feed: ${r.feed_views??'—'} · Exibido: ${r.shown_in_feed??'—'} · Média assistida: ${r.average_percentage??'—'}% · Continuaram: ${r.stayed_percentage??'—'}%</p><p>${esc(r.notes)}</p><p>${r.restriction==='blocked'?'Bloqueio informado no Studio. Consulte os detalhes da restrição.':r.feed_views===0?'Sem visualizações registradas pelo feed. Esse dado, sozinho, não comprova bloqueio.':'Compare a distribuição e a audiência com a restrição informada no Studio.'}</p><button class="btn btn-outline btn-sm" data-report="${i}">Editar registro</button></article>`).join(''):'<p>Ainda não há registros de publicação.</p>';history.querySelectorAll('[data-report]').forEach(b=>b.onclick=()=>{const r=records[Number(b.dataset.report)];Object.entries(r).forEach(([key,value])=>{if(form.elements[key])form.elements[key].value=value??'';});form.scrollIntoView({behavior:'smooth',block:'center'});});}
    form.onsubmit=async e=>{e.preventDefault();const button=form.querySelector('button[type=submit]');button.disabled=true;state.textContent='Salvando…';const data=Object.fromEntries(new FormData(form));for(const k of ['views','feed_views','shown_in_feed','average_percentage','stayed_percentage'])data[k]=data[k]===''?null:Number(data[k]);try{await request(`/api/top5-tools/${job.id}/reports`,json('PUT',data));await refresh();state.textContent='Registro salvo.';}catch(error){state.textContent=error.message;}finally{button.disabled=false;}};refresh().catch(e=>state.textContent=e.message);
  }
  window.TopFiveTools={entry,fill,beforeGenerate,mount};
})();
